### ISSUE TITLE
Code and database problem

### ISSUE THREAD

**Issue by jagdeepmalhi** [sathish43/LaravelInventry#1]
According to shared code and database base file name "Bckp_Local_Feb_16.sql" not updated.
Coding and database synchronisation problem.
Please share the update code and database file with some sample data.

Thanks

**Comment by sathishportfolio** [comment]
@jagdeepmalhi, the backup sql file is just for my own reference. You can directly do **php artisan migrate** and **php artisan db:seed** to make the code running

Thanks :)
