### ISSUE TITLE
I am new to laravel please provide installation instructions

### ISSUE THREAD

**Issue by parmindersingh1** [sathish43/LaravelInventry#2]
I am getting blank screen, i already ran 
composer install
npm install
php artisan migrate
php artisan db:seed

**Comment by sathishportfolio** [comment]
@parmindersingh1 Happy to help :)  Can you try using, php artisan serve

**Comment by parmindersingh1** [comment]
i am getting issue count(): Parameter must be an array or an object that implements Countable on php artisan db:seed command

**Comment by parmindersingh1** [comment]
it worked after updating laravel to 5.6 thank you

**Comment by SumanKhdka** [comment]
Hi, I am getting the same issue  count(): Parameter must be an array or an object that implements Countable on 'php artisan db:seed' command how can I solve this ?

**Comment by sathishportfolio** [comment]
Downgrade your PHP version to 5.6 or 7.1
