### ISSUE TITLE
Runtime Exception

### ISSUE THREAD

**Issue by samuelabate** [sathish43/LaravelInventry#3]
After cloning your project and running the migration, I got the following error:

>  **RuntimeException**
> The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths.

**Comment by sathishportfolio** [comment]
Run this commands on your terminal:

php artisan config:clear 
php artisan config:cache
php artisan key:generate

composer install
php artisan migrate
php artisan db:seed

**Note: make sure you have php version 5.6 - 7.1**

**Comment by samuelabate** [comment]
Thank you for your fast feedback! Looks like I forgot to generate the key.
